version: '3.9'

services:
  go-db.gowebbasics.com:
    container_name: db-gowebbasics
    image: queirozjamessom/gowebbasics/db
    volumes: ["./container/database/data:/var/lib/postgresql/data"]
    hostname: go-db.gowebbasics.com
    ports: ["5432:5432"]
    networks: ["gowebbasics"]
    build:
      context: ./container/database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: gopguser
      POSTGRES_PASSWORD: gopgpass
      POSTGRES_DB: gopgdb

